# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_auto_20170630_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_goods', related_query_name='type_goods', to='eshop.Type'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='keyword_goods', related_query_name='keyword_goods', to='eshop.Keyword'),
        ),
    ]
