# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_shop_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='RemittanceItem',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittanceitem_goods', related_query_name='remittanceitem_goods', to='eshop.RemittanceItem'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_goods', related_query_name='type_goods', to='eshop.Type'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='goods',
            name='shoppingCartItem',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoppingitem_goods', related_query_name='shoppingitem_goods', to='eshop.ShoppingCartItem'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
