# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_auto_20170705_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment', related_query_name='comments', to='eshop.RemittanceItem'),
        ),
    ]
