# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_auto_20170630_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', related_query_name='shop_goods', to='eshop.Shop'),
        ),
    ]
