# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_auto_20170630_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='keywords',
            new_name='keyword',
        ),
    ]
