# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_auto_20170630_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='keyword',
            field=models.ManyToManyField(related_name='keyword_goods', related_query_name='keyword_goods', to='eshop.Keyword'),
        ),
    ]
