# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_auto_20170630_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='RemittanceItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remittanceitem_goods', related_query_name='remittanceitem_goods', to='eshop.RemittanceItem'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_goods', related_query_name='type_goods', to='eshop.Type'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='shoppingCartItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoppingitem_goods', related_query_name='shoppingitem_goods', to='eshop.ShoppingCartItem'),
        ),
    ]
